#!/usr/bin/env python3
"""
TDD and BDD tests for commit diff report compilation (JSON → MDX).

TDD: Unit tests for compile output structure.
BDD: Acceptance scenarios (Given/When/Then) for compilation behavior.

Run: pytest tests/test_commit_diff_report_compile_tdd_bdd.py -v
"""
import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
REPORT_JSON = ROOT / "results" / "commit_diff_38ce1cd_report.json"
REPORT_MDX = ROOT / "results" / "commit_diff_38ce1cd_report.mdx"


class TestCompileProducesMdx:
    """TDD: compile_commit_diff_report.py produces valid MDX output."""

    @pytest.fixture(autouse=True)
    def ensure_report_json(self):
        if not REPORT_JSON.exists():
            proc = subprocess.run(
                [
                    sys.executable,
                    str(ROOT / "scripts" / "verify_commit_diff.py"),
                    "--skip-validate-qa",
                ],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=120,
            )
            assert proc.returncode == 0, f"verify_commit_diff failed: {proc.stderr}"
        proc = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "compile_commit_diff_report.py")],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert proc.returncode == 0, f"compile failed: {proc.stderr}"
        yield

    def test_compile_produces_mdx(self):
        """TDD: Compile produces MDX file."""
        assert REPORT_MDX.exists()

    def test_compile_has_frontmatter(self):
        """TDD: MDX has YAML frontmatter."""
        content = REPORT_MDX.read_text(encoding="utf-8")
        assert content.startswith("---")
        assert "title:" in content
        assert "base_commit:" in content
        assert "target:" in content
        assert "generated_at:" in content
        assert "---" in content[4:]  # closing frontmatter

    def test_compile_per_db_sections(self):
        """TDD: MDX has per-DB sections (### db-N)."""
        content = REPORT_MDX.read_text(encoding="utf-8")
        assert "### db-1" in content
        assert "### db-16" in content
        assert "**Source**" in content
        assert "**Client**" in content
        assert "**Sync**" in content

    def test_compile_consistent_format(self):
        """TDD: MDX has consistent structure (Summary, Per-DB Report, Raw Diff)."""
        content = REPORT_MDX.read_text(encoding="utf-8")
        assert "# Commit Diff Verification Report" in content
        assert "## Summary" in content
        assert "## Per-DB Report" in content
        assert "## Raw Diff" in content
        assert "Generated by compile_commit_diff_report.py" in content


class TestCompileBDDScenarios:
    """BDD: Given report JSON, When compile runs, Then output satisfies acceptance criteria."""

    @pytest.fixture(autouse=True)
    def run_compile(self):
        if not REPORT_JSON.exists():
            subprocess.run(
                [
                    sys.executable,
                    str(ROOT / "scripts" / "verify_commit_diff.py"),
                    "--skip-validate-qa",
                ],
                cwd=str(ROOT),
                capture_output=True,
                text=True,
                timeout=120,
            )
        proc = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "compile_commit_diff_report.py")],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=30,
        )
        assert proc.returncode == 0
        yield

    def test_given_report_json_when_compile_then_mdx_has_all_dbs(self):
        """BDD: Given report JSON, When compile runs, Then MDX output has all db-1..db-16."""
        with open(REPORT_JSON, encoding="utf-8") as f:
            report = json.load(f)
        db_ids = set(report.get("databases", {}).keys())

        content = REPORT_MDX.read_text(encoding="utf-8")
        for db_id in db_ids:
            assert f"### {db_id}" in content, f"{db_id} must be in MDX"

    def test_given_report_json_when_compile_then_data_consistent_with_json(self):
        """BDD: Given report JSON, When compile runs, Then MDX data matches JSON (e.g. total_dbs)."""
        with open(REPORT_JSON, encoding="utf-8") as f:
            report = json.load(f)
        total = report.get("summary", {}).get("total_dbs", 0)

        content = REPORT_MDX.read_text(encoding="utf-8")
        assert f"Total DBs: {total}" in content
