#!/usr/bin/env python3
"""
Compile repo_health.json to MDX format.

Usage:
    python3 scripts/compile_repo_health_mdx.py
    python3 scripts/compile_repo_health_mdx.py --input results/repo_health.json --output results/repo_health.mdx
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JSON = ROOT / "results" / "repo_health.json"
DEFAULT_OUT = ROOT / "results" / "repo_health.mdx"


def compile_to_mdx(report: dict) -> str:
    """Compile repo_health report dict to MDX string."""
    generated = report.get("generated_at", "")
    pass_val = report.get("Pass", 0)
    status = "PASS" if pass_val == 1 else "FAIL"

    lines = [
        "---",
        "title: Repo Health Report",
        "description: Data size, schema compliance, naming, and unnecessary files",
        f"generated_at: {generated}",
        f"Pass: {pass_val}",
        "---",
        "",
        "# Repo Health Report",
        "",
        f"**Status:** {status}",
        f"**Generated:** {generated}",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]

    checks = report.get("checks", {})
    size = checks.get("data_size_gb", {})
    total = size.get("total_bytes", 0)
    required = size.get("required_bytes", 1073741824)
    size_pass = size.get("Pass", 0)
    lines.append(f"- Data size: {total:,} / {required:,} bytes ({'Pass' if size_pass else 'Fail'})")
    lines.append(f"- Schema PostgreSQL compliant: {'Pass' if checks.get('schema_postgresql_compliant', {}).get('Pass') else 'Fail'}")
    lines.append(f"- Naming consistent: {'Pass' if checks.get('naming_consistent', {}).get('Pass') else 'Fail'}")
    src_flagged = checks.get("unnecessary_source_files", {}).get("flagged", {})
    src_count = sum(len(v) for v in src_flagged.values())
    lines.append(f"- Flagged unnecessary source files: {src_count}")
    root_flagged = checks.get("unnecessary_root_files", {}).get("flagged", [])
    lines.append(f"- Flagged unnecessary root files: {len(root_flagged)}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Data Size")
    lines.append("")
    lines.append(f"Total data.sql bytes: **{total:,}**")
    lines.append(f"Required: **{required:,}** (1GB)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Schema Compliance")
    lines.append("")
    schema = checks.get("schema_postgresql_compliant", {})
    violations = schema.get("violations", {})
    if violations:
        lines.append("**Violations (non-PostgreSQL types):**")
        lines.append("")
        for db_id, vlist in sorted(violations.items()):
            lines.append(f"- {db_id}: {', '.join(vlist)}")
        lines.append("")
    else:
        lines.append("All schemas are PostgreSQL compliant.")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Naming")
    lines.append("")
    naming = checks.get("naming_consistent", {})
    nviol = naming.get("violations", {})
    if nviol:
        lines.append("**Tables not snake_case:**")
        lines.append("")
        for db_id, vlist in sorted(nviol.items()):
            lines.append(f"- {db_id}: {', '.join(vlist)}")
        lines.append("")
    else:
        lines.append("All table names use snake_case.")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Flagged Unnecessary Files (source/db-N)")
    lines.append("")
    lines.append("Files/dirs not required for app/ compilation:")
    lines.append("")
    for db_id, paths in sorted(src_flagged.items(), key=lambda x: int(x[0].split("-")[1])):
        lines.append(f"### {db_id}")
        lines.append("")
        for p in paths[:20]:
            lines.append(f"- `{p}`")
        if len(paths) > 20:
            lines.append(f"- ... and {len(paths) - 20} more")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Flagged Unnecessary Files (repo root)")
    lines.append("")
    for p in root_flagged[:50]:
        lines.append(f"- `{p}`")
    if len(root_flagged) > 50:
        lines.append(f"- ... and {len(root_flagged) - 50} more")
    lines.append("")
    lines.append("*Generated by compile_repo_health_mdx.py. MDX-compatible markdown.*")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile repo health JSON to MDX")
    parser.add_argument("--input", "-i", default=str(DEFAULT_JSON))
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUT))
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Error: {in_path} not found. Run repo_health_check.py first.", file=sys.stderr)
        return 1

    with open(in_path, encoding="utf-8") as f:
        report = json.load(f)

    mdx_content = compile_to_mdx(report)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(mdx_content, encoding="utf-8")

    print(f"MDX report written to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
