#!/usr/bin/env python3
"""
Compile commit_diff_38ce1cd_report.json to MDX format.
Follows same pattern as queries.json → queries.md.

Usage:
    python3 scripts/compile_commit_diff_report.py
    python3 scripts/compile_commit_diff_report.py --input results/commit_diff_38ce1cd_report.json --output results/commit_diff_38ce1cd_report.mdx
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JSON = ROOT / "results" / "commit_diff_38ce1cd_report.json"
DEFAULT_RAW = ROOT / "results" / "commit_diff_38ce1cd_raw.txt"
DEFAULT_OUT = ROOT / "results" / "commit_diff_38ce1cd_report.mdx"


def compile_to_mdx(report: dict, raw_diff_path: Path | None = None) -> str:
    """Compile report dict to MDX string."""
    base = report.get("base_commit", "")[:7]
    target = report.get("target", "HEAD")
    generated = report.get("generated_at", "")

    lines = [
        "---",
        f"title: Commit Diff Verification Report — {base} vs {target}",
        "description: Per-DB, per-section, per-key comparison of source/ and client/",
        f"base_commit: {report.get('base_commit', '')}",
        f"target: {target}",
        f"generated_at: {generated}",
        "---",
        "",
        "# Commit Diff Verification Report",
        "",
        f"**Base commit:** {base}",
        f"**Target:** {target}",
        "**Scope:** source/, client/",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]

    s = report.get("summary", {})
    total = s.get("total_dbs", 0)
    val_pass = sum(1 for v in s.get("validation_pass", {}).values() if v == 1)
    qa_pass = sum(1 for v in s.get("qa_pass", {}).values() if v == 1)
    lines.append(f"- Total DBs: {total}")
    lines.append(f"- Validation pass: {val_pass}")
    lines.append(f"- QA pass: {qa_pass}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Per-DB Report")
    lines.append("")

    for db_id in sorted(report.get("databases", {}).keys(), key=lambda x: (int(x.split("-")[1]) if "-" in x else 0)):
        db_data = report["databases"][db_id]
        lines.append(f"### {db_id}")
        lines.append("")

        # Source
        lines.append("**Source**")
        src = db_data.get("source", {})
        for sec in ["app/DATABASE", "app/DOCUMENTATION", "app/QUERIES"]:
            if sec in src and isinstance(src[sec], dict):
                summary = src[sec].get("summary", "")
                lines.append(f"- {sec}: {summary}")
        lines.append("")

        # Client
        lines.append("**Client**")
        cli = db_data.get("client", {})
        for sec in ["DATABASE", "DOCUMENTATION", "QUERIES"]:
            if sec in cli and isinstance(cli[sec], dict):
                summary = cli[sec].get("summary", "")
                lines.append(f"- {sec}: {summary}")
        lines.append("")

        # Sync
        lines.append("**Sync**")
        sync = db_data.get("source_vs_client_sync", {})
        for sec in ["DATABASE", "QUERIES"]:
            if sec in sync:
                in_sync = sync[sec].get("in_sync", True)
                lines.append(f"- {sec}: {'in sync' if in_sync else 'mismatched'}")
        lines.append("")

        # key_diff_summary (from source app/QUERIES)
        qsec = src.get("app/QUERIES", {})
        qj = qsec.get("queries.json") if isinstance(qsec, dict) else None
        if isinstance(qj, dict) and qj.get("key_diff_summary"):
            lines.append("**queries.json key_diff_summary**")
            lines.append("")
            lines.append("| Key | Queries Changed |")
            lines.append("|-----|-----------------|")
            for k, v in sorted(qj["key_diff_summary"].items()):
                lines.append(f"| {k} | {v} |")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Raw diff
    if raw_diff_path and raw_diff_path.exists():
        lines.append("## Raw Diff")
        lines.append("")
        raw_content = raw_diff_path.read_text(encoding="utf-8")
        excerpt = raw_content[:2000] + "..." if len(raw_content) > 2000 else raw_content
        lines.append("```text")
        lines.append(excerpt.strip())
        lines.append("```")
        lines.append("")
    else:
        lines.append("## Raw Diff")
        lines.append("")
        lines.append("See `results/commit_diff_38ce1cd_raw.txt`")
        lines.append("")

    lines.append("*Generated by compile_commit_diff_report.py. MDX-compatible markdown.*")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile commit diff report JSON to MDX")
    parser.add_argument("--input", "-i", default=str(DEFAULT_JSON))
    parser.add_argument("--output", "-o", default=str(DEFAULT_OUT))
    parser.add_argument("--raw", "-r", default=str(DEFAULT_RAW), help="Raw diff file path")
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"Error: {in_path} not found. Run verify_commit_diff.py first.", file=sys.stderr)
        return 1

    with open(in_path, encoding="utf-8") as f:
        report = json.load(f)

    raw_path = Path(args.raw)
    mdx_content = compile_to_mdx(report, raw_path)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(mdx_content, encoding="utf-8")

    print(f"MDX report written to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
