#!/usr/bin/env python3
"""
Create a test notebook specifically for Colab testing
This notebook can be uploaded to Colab to verify everything works
"""

import json
from pathlib import Path

def detect_base_dir():
    """Detect base directory."""
    cwd = Path.cwd()
    if cwd.name == 'scripts' and (cwd.parent / 'db-6').exists():
        return cwd.parent
    return cwd.parent if (cwd.parent / 'db-6').exists() else cwd

BASE_DIR = detect_base_dir()

def create_colab_test_notebook():
    """Create a comprehensive Colab test notebook."""
    
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Google Colab Test Notebook\n",
                    "\n",
                    "This notebook tests all Colab-specific functionality.\n",
                    "\n",
                    "## Test Checklist\n",
                    "- ✅ Colab environment detection\n",
                    "- ✅ PostgreSQL installation\n",
                    "- ✅ PostgreSQL connection\n",
                    "- ✅ File path detection\n",
                    "- ✅ Package imports\n",
                    "- ✅ SQL query execution"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 1: Colab Environment Detection\n",
                    "# ============================================================================\n",
                    "\n",
                    "import sys\n",
                    "import os\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"COLAB ENVIRONMENT DETECTION TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "IS_COLAB = False\n",
                    "\n",
                    "# Method 1: Try importing google.colab\n",
                    "try:\n",
                    "    import google.colab\n",
                    "    IS_COLAB = True\n",
                    "    print(\"✅ Method 1: google.colab import successful\")\n",
                    "except ImportError:\n",
                    "    print(\"❌ Method 1: google.colab import failed\")\n",
                    "\n",
                    "# Method 2: Check COLAB_GPU environment variable\n",
                    "if os.environ.get('COLAB_GPU'):\n",
                    "    IS_COLAB = True\n",
                    "    print(\"✅ Method 2: COLAB_GPU environment variable found\")\n",
                    "else:\n",
                    "    print(\"⚠️  Method 2: COLAB_GPU not found\")\n",
                    "\n",
                    "# Method 3: Check /content directory\n",
                    "if os.path.exists('/content'):\n",
                    "    IS_COLAB = True\n",
                    "    print(\"✅ Method 3: /content directory exists\")\n",
                    "else:\n",
                    "    print(\"❌ Method 3: /content directory not found\")\n",
                    "\n",
                    "print(f\"\\n{'='*80}\")\n",
                    "if IS_COLAB:\n",
                    "    print(\"✅ COLAB ENVIRONMENT CONFIRMED\")\n",
                    "else:\n",
                    "    print(\"❌ NOT RUNNING IN COLAB\")\n",
                    "    print(\"   This notebook requires Google Colab\")\n",
                    "print(\"=\"*80)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 2: PostgreSQL Installation\n",
                    "# ============================================================================\n",
                    "\n",
                    "import subprocess\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"POSTGRESQL INSTALLATION TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "# Check if PostgreSQL is already installed\n",
                    "try:\n",
                    "    result = subprocess.run(['which', 'psql'], capture_output=True, text=True)\n",
                    "    if result.returncode == 0:\n",
                    "        print(\"✅ PostgreSQL already installed\")\n",
                    "        print(f\"   Location: {result.stdout.strip()}\")\n",
                    "    else:\n",
                    "        print(\"⚠️  PostgreSQL not found - will install\")\n",
                    "except Exception as e:\n",
                    "    print(f\"⚠️  Could not check PostgreSQL: {e}\")\n",
                    "\n",
                    "# Install PostgreSQL\n",
                    "print(\"\\nInstalling PostgreSQL...\")\n",
                    "try:\n",
                    "    subprocess.run(['apt-get', 'update'], check=True, capture_output=True)\n",
                    "    print(\"✅ apt-get update successful\")\n",
                    "    \n",
                    "    subprocess.run(['apt-get', 'install', '-y', 'postgresql', 'postgresql-contrib'], \n",
                    "                   check=True, capture_output=True)\n",
                    "    print(\"✅ PostgreSQL installation successful\")\n",
                    "except subprocess.CalledProcessError as e:\n",
                    "    print(f\"❌ PostgreSQL installation failed: {e}\")\n",
                    "except Exception as e:\n",
                    "    print(f\"❌ Error: {e}\")\n",
                    "\n",
                    "# Start PostgreSQL service\n",
                    "print(\"\\nStarting PostgreSQL service...\")\n",
                    "try:\n",
                    "    subprocess.run(['service', 'postgresql', 'start'], check=True, capture_output=True)\n",
                    "    print(\"✅ PostgreSQL service started\")\n",
                    "except Exception as e:\n",
                    "    print(f\"❌ Failed to start PostgreSQL: {e}\")\n",
                    "\n",
                    "# Verify PostgreSQL is running\n",
                    "print(\"\\nVerifying PostgreSQL is running...\")\n",
                    "try:\n",
                    "    result = subprocess.run(['pg_isready'], capture_output=True, text=True)\n",
                    "    if result.returncode == 0:\n",
                    "        print(\"✅ PostgreSQL is ready\")\n",
                    "        print(f\"   {result.stdout.strip()}\")\n",
                    "    else:\n",
                    "        print(\"❌ PostgreSQL is not ready\")\n",
                    "        print(f\"   {result.stderr.strip()}\")\n",
                    "except Exception as e:\n",
                    "    print(f\"❌ Error checking PostgreSQL: {e}\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 3: PostgreSQL Connection\n",
                    "# ============================================================================\n",
                    "\n",
                    "import psycopg2\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"POSTGRESQL CONNECTION TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "try:\n",
                    "    conn = psycopg2.connect(\n",
                    "        host='localhost',\n",
                    "        port=5432,\n",
                    "        user='postgres',\n",
                    "        password='postgres',\n",
                    "        database='postgres'\n",
                    "    )\n",
                    "    print(\"✅ PostgreSQL connection successful\")\n",
                    "    print(f\"   Host: localhost\")\n",
                    "    print(f\"   Port: 5432\")\n",
                    "    print(f\"   User: postgres\")\n",
                    "    \n",
                    "    # Test query\n",
                    "    cursor = conn.cursor()\n",
                    "    cursor.execute(\"SELECT version();\")\n",
                    "    version = cursor.fetchone()[0]\n",
                    "    print(f\"\\n✅ PostgreSQL version: {version[:50]}...\")\n",
                    "    \n",
                    "    cursor.close()\n",
                    "    conn.close()\n",
                    "    print(\"\\n✅ Connection closed successfully\")\n",
                    "    \n",
                    "except psycopg2.OperationalError as e:\n",
                    "    print(f\"❌ Connection failed: {e}\")\n",
                    "    print(\"\\nTroubleshooting:\")\n",
                    "    print(\"1. Make sure PostgreSQL is installed\")\n",
                    "    print(\"2. Make sure PostgreSQL service is running\")\n",
                    "    print(\"3. Try: !service postgresql restart\")\n",
                    "except Exception as e:\n",
                    "    print(f\"❌ Error: {e}\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 4: File Path Detection\n",
                    "# ============================================================================\n",
                    "\n",
                    "from pathlib import Path\n",
                    "import os\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"FILE PATH DETECTION TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "# Check Colab paths\n",
                    "colab_paths = [\n",
                    "    Path('/content'),\n",
                    "    Path('/content/drive'),\n",
                    "    Path('/content/drive/MyDrive'),\n",
                    "]\n",
                    "\n",
                    "print(\"\\nChecking Colab paths:\")\n",
                    "for path in colab_paths:\n",
                    "    if path.exists():\n",
                    "        print(f\"✅ {path} exists\")\n",
                    "    else:\n",
                    "        print(f\"⚠️  {path} does not exist\")\n",
                    "\n",
                    "# Check current working directory\n",
                    "print(f\"\\nCurrent working directory: {Path.cwd()}\")\n",
                    "\n",
                    "# Test recursive file finding\n",
                    "print(\"\\nTesting recursive file finding:\")\n",
                    "test_file = 'queries.json'\n",
                    "search_paths = [\n",
                    "    Path('/content'),\n",
                    "    Path('/content/drive/MyDrive'),\n",
                    "    Path.cwd(),\n",
                    "]\n",
                    "\n",
                    "found = False\n",
                    "for search_path in search_paths:\n",
                    "    if search_path.exists():\n",
                    "        try:\n",
                    "            for file_path in search_path.rglob(test_file):\n",
                    "                if file_path.is_file():\n",
                    "                    print(f\"✅ Found {test_file} at: {file_path}\")\n",
                    "                    found = True\n",
                    "                    break\n",
                    "        except Exception as e:\n",
                    "            print(f\"⚠️  Error searching {search_path}: {e}\")\n",
                    "\n",
                    "if not found:\n",
                    "    print(f\"⚠️  {test_file} not found (this is OK if not uploaded)\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 5: Package Imports\n",
                    "# ============================================================================\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"PACKAGE IMPORT TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "packages = [\n",
                    "    ('pandas', 'pd'),\n",
                    "    ('numpy', 'np'),\n",
                    "    ('psycopg2', 'psycopg2'),\n",
                    "    ('matplotlib.pyplot', 'plt'),\n",
                    "    ('seaborn', 'sns'),\n",
                    "    ('IPython.display', None),\n",
                    "]\n",
                    "\n",
                    "print(\"\\nTesting imports:\")\n",
                    "for package, alias in packages:\n",
                    "    try:\n",
                    "        if alias:\n",
                    "            exec(f\"import {package} as {alias}\")\n",
                    "            print(f\"✅ {package} imported as {alias}\")\n",
                    "        else:\n",
                    "            exec(f\"from {package} import *\")\n",
                    "            print(f\"✅ {package} imported\")\n",
                    "    except ImportError as e:\n",
                    "        print(f\"❌ Failed to import {package}: {e}\")\n",
                    "        print(f\"   Install with: !pip install {package.split('.')[0]}\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ============================================================================\n",
                    "# TEST 6: SQL Query Execution\n",
                    "# ============================================================================\n",
                    "\n",
                    "import psycopg2\n",
                    "import pandas as pd\n",
                    "import time\n",
                    "\n",
                    "print(\"=\"*80)\n",
                    "print(\"SQL QUERY EXECUTION TEST\")\n",
                    "print(\"=\"*80)\n",
                    "\n",
                    "# Test simple query\n",
                    "test_query = \"SELECT 1 as test_value, 'Hello Colab' as message;\"\n",
                    "\n",
                    "try:\n",
                    "    conn = psycopg2.connect(\n",
                    "        host='localhost',\n",
                    "        port=5432,\n",
                    "        user='postgres',\n",
                    "        password='postgres',\n",
                    "        database='postgres'\n",
                    "    )\n",
                    "    \n",
                    "    cursor = conn.cursor()\n",
                    "    \n",
                    "    start_time = time.time()\n",
                    "    cursor.execute(test_query)\n",
                    "    execution_time = time.time() - start_time\n",
                    "    \n",
                    "    columns = [desc[0] for desc in cursor.description]\n",
                    "    rows = cursor.fetchall()\n",
                    "    \n",
                    "    df = pd.DataFrame(rows, columns=columns)\n",
                    "    \n",
                    "    print(f\"✅ Query executed successfully\")\n",
                    "    print(f\"   Execution time: {execution_time:.4f} seconds\")\n",
                    "    print(f\"   Rows returned: {len(df)}\")\n",
                    "    print(f\"   Columns: {', '.join(columns)}\")\n",
                    "    print(f\"\\nResults:\")\n",
                    "    print(df.to_string())\n",
                    "    \n",
                    "    cursor.close()\n",
                    "    conn.close()\n",
                    "    \n",
                    "except Exception as e:\n",
                    "    print(f\"❌ Query execution failed: {e}\")\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## Test Summary\n",
                    "\n",
                    "If all tests passed:\n",
                    "- ✅ Colab environment detected\n",
                    "- ✅ PostgreSQL installed and running\n",
                    "- ✅ PostgreSQL connection working\n",
                    "- ✅ File paths detected\n",
                    "- ✅ All packages imported\n",
                    "- ✅ SQL queries executing\n",
                    "\n",
                    "**Your notebooks are ready for Colab!**"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    # Save notebook
    output_path = BASE_DIR / 'colab_test_notebook.ipynb'
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    
    print(f"✅ Created Colab test notebook: {output_path}")
    print("\\nUpload this notebook to Google Colab to test all functionality!")
    
    return output_path

if __name__ == '__main__':
    create_colab_test_notebook()
