#!/usr/bin/env python3
"""
Timestamp utilities for validation suite
All JSON files generated by validation suite must use EST timestamps in YYYYMMDD-HHMM format
"""

from datetime import datetime
import time

try:
    import pytz
    PYTZ_AVAILABLE = True
except ImportError:
    PYTZ_AVAILABLE = False

def get_est_timestamp() -> str:
    """
    Get current timestamp in EST timezone, formatted as YYYYMMDD-HHMM

    Returns:
        str: Timestamp in format YYYYMMDD-HHMM (EST)

    Example:
        >>> get_est_timestamp()
        '20260203-1430'
    """
    if PYTZ_AVAILABLE:
        # Use pytz for accurate timezone handling (handles EST/EDT automatically)
        est = pytz.timezone('US/Eastern')
        est_now = datetime.now(est)
        return est_now.strftime('%Y%m%d-%H%M')
    else:
        # Fallback: Calculate EST offset manually
        # EST is UTC-5, EDT is UTC-4
        # Simple approximation: assume EST (UTC-5) for now
        # Note: This doesn't handle DST automatically, but pytz should be preferred
        utc_now = datetime.utcnow()
        # EST is UTC-5 hours
        est_offset_hours = 5
        est_now = utc_now.replace(hour=(utc_now.hour - est_offset_hours) % 24)
        return est_now.strftime('%Y%m%d-%H%M')

def get_est_datetime() -> datetime:
    """
    Get current datetime object in EST timezone

    Returns:
        datetime: Current datetime in EST timezone
    """
    if PYTZ_AVAILABLE:
        est = pytz.timezone('US/Eastern')
        return datetime.now(est)
    else:
        # Fallback: return UTC with manual offset
        utc_now = datetime.utcnow()
        # EST is UTC-5 hours
        est_offset_hours = 5
        est_now = utc_now.replace(hour=(utc_now.hour - est_offset_hours) % 24)
        return est_now
